### ISSUE TITLE
postprocessing which mhd file

### ISSUE THREAD

**Issue by chenjx1005** [Connor323/Lung-Lobes-Segmentation-in-CT-Scans#1]
thank you for your sharing. In the Postprocessing for fissure enhancement cell, I don't know which mhd file I should use when I perform region growing and vector region growing. Could you give me   step by step instructions like:
`./region_growing xxx.mhd temp.mhd`
`./vector_region_growing temp.mhd vessel_rg.mhd`

Thanks!

**Comment by Connor323** [comment]
Hi, sorry for my late response... The purpose for Hessian vector region growing is to extract the fissures and the intensity-based region growing is for removing small noise segments; therefore, you need to do the vector first and then do the intensity. 
1) ./vector_region_growing original_CT_data.mhd fissure_extract_raw.mhd
2) ./region_growing fissure_extract_raw.mhd fissure_extract_refined.mhd

Moreover, if you want you can use the script in ipython notebook under the post-process section to further refine the results of "fissure_extract_refined.mhd" using morphological operations. 

Sorry about the confusion and please feel free to let me know if anything that I can help! :)

**Comment by chenjx1005** [comment]
thank you!
